baseurl: ""
url: "https://vnegrisolo.github.io"
name: Vinicius Ferreira Negrisolo
email: vinicius.negrisolo@gmail.com
twitter_username: vfnegrisolo
github_username: vnegrisolo
linkedin_uri: vinicius-ferreira-negrisolo-53146a38
markdown: kramdown
languages:
  - en
  - pt
permalink: /:categories/:title
