baseurl: ""
url: "https://vnegrisolo.github.io/"
email: vinicius.negrisolo@gmail.com
twitter_username: vfnegrisolo
github_username:  vnegrisolo
markdown: kramdown
languages:
  - en
  - pt
permalink: /:categories/:title
